### PR TITLE
Added listpkgs.html and did some cleaning up.

### PR DESCRIPTION
**Pull request by junland**
Did some clean up and added a list all applications / pkgs. Still need to work out a API but were getting there.

### CODE REVIEW

**Comment by andersevenrud** [comment]
Cool. I'll clone this locally and have a look :)

**Comment by junland** [comment]
Thanks, could you look at allpkgs.html. Having trouble getting json to display on the table.

**Comment by andersevenrud** [comment]
Just comitted 1fd07c1f4ca3c6fc0034d40712eee5f9fcfc7b6c. Fixes table rendering.

Getting this error in console:

> Uncaught SyntaxError: Unexpected token (materialize.min.js:910)

Seems weird.

**Comment by junland** [comment]
@andersevenrud Thanks.

> Getting this error in console:
>     Uncaught SyntaxError: Unexpected token (materialize.min.js:910)
> Seems weird.

Getting that too. 910 is pointing to line 910 in that js file. I'll go file a issue with the Materialize Project.

**Comment by andersevenrud** [comment]
First check if there is a newer version available :)

**Comment by junland** [comment]
Will do :)

**Comment by junland** [comment]
Yea 0.97 is the current, and that's what were running right now. I haven't made any changes to the source files except the color of the navbar in the CSS file

You can view the issue here: https://github.com/Dogfalo/materialize/issues/1776

**Comment by andersevenrud** [comment]
Did you build this materialize lib yourself ? Or was it just a prebuilt download ?
Also was the changes to javascript ? If so, you might have broken something there.

**Comment by junland** [comment]
It was a prebuilt download. Maybe I did something wrong in the <head> tags?

`<head>`
`<!--Import materialize.css-->`
`<link type="text/css" rel="stylesheet" href="css/materialize.min.css" media="screen,projection" />`

`<!--Let browser know website is optimized for mobile-->`
`<meta name="viewport" content="width=device-width, initial-scale=1.0" />`

`<!--Import jQuery before materialize.js-->`
`<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>`
`<script type="text/javascript" src="js/materialize.min.js"></script>`
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`
`</head>`

**Comment by andersevenrud** [comment]
It's a syntax error, so it's a problem in the build. I added a patch in the issue you made.

**Comment by junland** [comment]
Yeaaaaa, It's such a small syntax error that no wonder I assumed it was on there end. Lol.

**Pull request merged**
